INSERT INTO games (slug, title, status, leaderboard_enabled, leaderboard_direction)
VALUES
  ('coldplay-canoodle', 'Coldplay Canoodle', 'published', 0, 'desc'),
  ('ctn', 'Crypto Tax Nightmare', 'published', 0, 'desc'),
  ('windows', 'Windows Didn''t Load Correctly', 'published', 0, 'desc'),
  ('tallgrass', 'Tall Grass', 'published', 0, 'desc'),
  ('chonksisyphus', 'Sisyphus Chonk', 'published', 0, 'desc'),
  ('oil', 'Oil & Epstein', 'published', 0, 'desc'),
  ('loki', 'Loki Is Genderfluid', 'published', 0, 'desc'),
  ('pong', 'Anybody // Pong', 'published', 0, 'desc'),
  ('rcs', 'Right-Click Save Kill', 'published', 0, 'desc'),
  ('kevin', 'Kevin', 'published', 0, 'desc'),
  ('fuckice', 'FUCK ICE', 'published', 0, 'desc'),
  ('bubble', 'YOU ARE BUBBLE', 'published', 0, 'desc'),
  ('cyber', 'Cyber Sunshine Smash', 'published', 0, 'desc'),
  ('punkmatch', 'game. punk. match.', 'published', 0, 'desc'),
  ('beepleblox', 'Beeple Blox', 'published', 0, 'desc'),
  ('doge', 'Goodbye, Kabosu', 'published', 0, 'desc'),
  ('girlscouts', 'ScoutSort', 'published', 0, 'desc'),
  ('dream', 'Mouth Dream', 'published', 0, 'desc'),
  ('kombatice', 'Kombat Ice', 'published', 0, 'desc'),
  ('lidstaysclosed', 'The Lid Stays Closed', 'published', 0, 'desc'),
  ('meelode', 'LodeMeeRunnerBits', 'published', 0, 'desc'),
  ('synthsnow', 'SynthSnow', 'published', 0, 'desc'),
  ('protectgreenland', 'Protect Greenland', 'published', 0, 'desc'),
  ('penisvagina', 'Penis // Vagina', 'published', 0, 'desc'),
  ('punksinspace', 'Punks In Space', 'published', 1, 'asc'),
  ('towerofpunks', 'Tower of Punks', 'published', 0, 'desc'),
  ('armfulofpunks', 'Armful of Punks', 'published', 0, 'desc'),
  ('punkfling', 'Punk Fling', 'published', 0, 'desc'),
  ('dontscroll', 'Don''t Scroll', 'published', 0, 'desc'),
  ('perilouspenguin', 'Perilous Penguin', 'published', 0, 'desc'),
  ('flighttosfo', 'Flight To SFO', 'published', 0, 'desc'),
  ('meebitsmountain', 'Meebits Mountain', 'published', 0, 'desc'),
  ('100goombas', '100 Goombas', 'published', 0, 'desc'),
  ('sledding', 'SLEDDING', 'published', 1, 'asc'),
  ('hell', 'Lindsay Graham In Hell', 'published', 1, 'asc')
ON CONFLICT(slug) DO UPDATE SET
  title = excluded.title,
  status = excluded.status,
  leaderboard_enabled = excluded.leaderboard_enabled,
  leaderboard_direction = excluded.leaderboard_direction,
  updated_at = CURRENT_TIMESTAMP;
